### ISSUE TITLE
Doesn't work with grunt-newer

### ISSUE THREAD

**Issue by sanket-webmavens** [1000ch/grunt-cwebp#16]
Grunt-newer doesn't work with grunt-cwebp. This is my configuration:

```js
cwebp: {
    my_target: {
        options: {
            q: 65
        },
        files: [{ // converting all files in webp formate in "assets/img" folder dynamically to relavant folder
        	expand: true,
            cwd: 'assets/img',
            src: ['**/*.{png,jpg}'],
            dest: 'dist/webp/'
        }]
    }
}
```

Please help, its working fine with grunt-contrib-imagemin

**Comment by 1000ch** [comment]
I'm still not sure what is the exact problem, but I guess the configuration should be aligned to the `grunt-newer` way described on [the README](https://github.com/tschaub/grunt-newer#the-newer-task), and I feel the failure was not caused by this plugin.
